<?php

/**
 * @file
 * Primary module hooks for Atwork Poll module.
 */

/**
 * Implements hook_template_preprocess_default_variables_alter() for poll-vote.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - form: The renderable form array for the poll voting form.
 */
function atworknext_preprocess_poll_vote(&$variables) {
	$form = $variables['form'];
	$poll_body = $form['#entity']->get('field_body')->getValue();
	$variables['poll_body'] = $poll_body[0]['value'];
}