<?php

namespace Drupal\atwork_idir_update;
/**
 * Implements hook_cron()
 */
function atwork_idir_udpate_cron() 
{ 
  // Hooking into cron every morning at 6am
  if( date('G') == 6 )
  {
    // Instantiate a new singleton class controller to fire up our idir update.
    $atwork_idir_update = new AtworkIdirUpdateController;
    $atwork_idir_update->AtworkIdirInit();
  }
  // TODO: Make sure we run this everyday - we may need to check the last-run status to make sure we have run it within the past 12 hours.
}