<?php
use Drupal\atwork_idir_update\Controller\AtworkIdirUpdateController;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_cron()
 */
function atwork_idir_update_cron()
{ 
  //kint("Hook got picked up");
    // We access our configuration.
  //$cron_config = \Drupal::configFactory()->getEditable('atwork_idir_update.settings');
  // Instantiate a new singleton class controller to fire up our idir update.
  $atwork_idir_update = new AtworkIdirUpdateController;
  $atwork_idir_update->main();
  // Hooking into cron every morning at 6am
}

function atwork_idir_update_cronapi($op, $job=null)
{
  return array(
    'atwork_idir_update_cronjob__1' => array(
      'title' => 'Idir-1 Handler',
      'callback' => 'atwork_idir_update_cron_test',
      'scheduler' => array(
        'name' => 'crontab',
        'crontab' => array(
          'rules' => array('15 6 * * *')
        ),
      ),
    ),
  );
}


/**
 * Implements hook_help().
 */
function atwork_idir_update_help( $route_name, RouteMatchInterface $route_match )
{
  switch ( $route_name ) 
  {
    case 'help.page.atwork_idir_update':
      return t('
        <h2>Idir update module for Drupal 8. </h2>
        <h3>Instructions:</h3>
        <p>After placing module in the <em>Modules</em> folder, Enable module under Custom on the <em>extend</em> page.</p>
        <p>This module is built to work with <a href="https://www.drupal.org/project/ultimate_cron" target="_blank">Ultimate Cron.</a></p>
        <p>The module can also be manually run by hitting the route admin.idir (example.com/admin/idir).</p>
      ');
  }
}