<?php

use Drupal\atwork_mail_send_update\Controller\AtworkMailSendUpdateController;

/**
 * @file
 * Contains atwork_mail_send_update.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function atwork_mail_send_update_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the atwork_mail_send_update module.
    case 'help.page.atwork_mail_send_update':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A cron hook that allows us to keep our newsletter and subscription lists current.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Cron callback, kick-starting the queue.
 */
function atwork_mail_send_update_callback(){
  \Drupal::logger('atwork_mail_send_update')->notice('Beginning email and newsletter subscription updates.');
  $update = new AtworkMailSendUpdateController();
  $update->main();
  \Drupal::logger('atwork_mail_send_update')->notice('Finished email and newsletter subscription updates.');
}
