<?php

use Drupal\group\Entity\GroupContent;
use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for atwork_article module.
 *
 */


/**
 * Implements hook_preprocess_HOOK().
 * 
 */
function atworknext_preprocess_node__group_post(&$variables) {
	// Get the group info for the group content (post)
	// NOTE: This will only work if the cardinality in the Group node (Group Post) plugin is set to 1.
	if ($variables['node']->getType() == 'group_post' && $variables['view_mode'] == 'full') {
		foreach (GroupContent::loadByEntity($variables['node']) as $group_content) {
			if($variables['node']->id() == $group_content->getEntity()->id()) $variables['label'] = $group_content->getGroup()->label();
		}
	}
	
	// Load Related Content Block
	$block = \Drupal\block\Entity\Block::load('views_block__related_content_block_3');
	$block_content = \Drupal::entityTypeManager()
	->getViewBuilder('block')
	->view($block);
	$variables['related_content'] = $block_content;
}

/**
 * Implements hook_preprocess_HOOK().
 *
 */
function atworknext_preprocess_page__group__galleries(&$variables) {
	//if ($variables['node']->getType() == 'group_post' && $variables['view_mode'] == 'full') {
	//	foreach (GroupContent::loadByEntity($variables['node']) as $group_content) {
	//		if($variables['node']->id() == $group_content->getEntity()->id()) $variables['label'] = $group_content->getGroup()->label();
	//	}
	//}
}

/**
* Implements hook_preprocess_HOOK().
*
*/
function atworknext_preprocess_breadcrumb__group_post(&$variables) {
	// Get the group info for the group content (post)
	// NOTE: This will only work if the cardinality in the Group node (Group Post) plugin is set to 1.
	//if ($variables['node']->getType() == 'group_post' && $variables['view_mode'] == 'full') {
	//	foreach (GroupContent::loadByEntity($variables['node']) as $group_content) {
	//		if($variables['node']->id() == $group_content->getEntity()->id()) $variables['label'] = $group_content->getGroup()->label();
	//	}
	//}
}

/**
 * Implements hook_preprocess_HOOK().
 *
 */
function atworknext_preprocess_group(&$variables) {
	// Load Related Content Block
	$block = \Drupal\block\Entity\Block::load('views_block__related_content_block_3');
	$block_content = \Drupal::entityTypeManager()
	->getViewBuilder('block')
	->view($block);
	$variables['related_content'] = $block_content;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 * 
 */
function atworknext_theme_suggestions_breadcrumb_alter(array &$suggestions, array $variables) {
	if ($node = \Drupal::routeMatch()->getParameter('node')) {
		$content_type = $node->bundle();
		$suggestions[] = 'breadcrumb__'.$content_type;
	}
}

/**
 * Implements hook_form_FORM_ID_alter.
 * 
 */

//function atworknext_form__alter(&$form, $form_state, $form_id) {
//	
//}
