<?php

use Drupal\group\Entity\GroupContent;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\Entity\BaseFieldOverride;
use Drupal\redirect\Entity\Redirect;
use Drupal\group\Entity\Group;

/**
 * @file
 * Primary module hooks for atwork_article module.
 *
 */

/**
 * Implements hook_preprocess_HOOK().
 * 
 */
function atworknext_preprocess_node__group_post(&$variables) {
	// Get the group info for the group content (post)
	// NOTE: This will only work if the cardinality in the Group node (Group Post) plugin is set to 1.
	if ($variables['node']->getType() == 'group_post' && $variables['view_mode'] == 'full') {
		foreach (GroupContent::loadByEntity($variables['node']) as $group_content) {
			if($variables['node']->id() == $group_content->getEntity()->id()) $variables['label'] = $group_content->getGroup()->label();
		}
	}
	
	// Load Related Content Block
	$block = \Drupal\block\Entity\Block::load('views_block__related_content_block_3');
	$block_content = \Drupal::entityTypeManager()
	->getViewBuilder('block')
	->view($block);
	$variables['related_content'] = $block_content;
}

/**
 * Implements hook_preprocess_HOOK().
 *
 */
function atworknext_preprocess_page__group__galleries(&$variables) {
	// TODO: Build the label for the group-title banner  
}

/**
 * Implements hook_preprocess_HOOK().
 *
 */
function atworknext_preprocess_group(&$variables) {
	// Is the user a member of this group?
	if($variables['group']->getMember(\Drupal::currentUser()->getAccount())) {
		$variables['member'] = TRUE;
	} else {
		$variables['member'] = FALSE;
	}
	
	$group = Group::load($variables['group']->id());
	
	$group_id = $group->id();
	$group_label = $group->get('label')->getValue()[0]['value'];
	
	// Add links to group content forms.
	$linkObject = Link ::createFromRoute(t('Create New Post'), 'entity.group_content.create_form', ["group" => $group_id,'plugin_id' => 'group_node:group_post']);
	$variables['post_link'] = $linkObject->toRenderable();
	
	$linkObject = Link ::createFromRoute(t('Create New Photo Gallery'), 'entity.group_content.create_form', ["group" => $group_id,'plugin_id' => 'group_node:photos']);
	$variables['photos_link'] = $linkObject->toRenderable();
	
	$linkObject = Link ::createFromRoute(t('Join Group'), 'entity.group.join', ["group" => $group_id]);
	$variables['join_link'] = $linkObject->toRenderable();
	
	$linkObject = Link ::createFromRoute(t('Leave Group'), 'entity.group.leave', ["group" => $group_id]);
	$variables['leave_link'] = $linkObject->toRenderable();
	
	$linkObject = Link ::createFromRoute(t('View All Photo Galleries'), 'view.related_content.page_2', ["arg_0" => $group_id]);
	$variables['photo_galleries'] = $linkObject->toRenderable();
	
	$linkObject = Link ::createFromRoute(t('View All Posts'), 'view.related_content.page_1', ["arg_0" => $group_label]);
	$variables['group_posts'] = $linkObject->toRenderable();
	
	// Load Related Content Block
	$block = \Drupal\block\Entity\Block::load('views_block__related_content_block_3');
	$block_content = \Drupal::entityTypeManager()
	->getViewBuilder('block')
	->view($block);
	$variables['related_content'] = $block_content;
}

/**
 * Implements hook_preprocess_HOOK().
 *
 */
function atworknext_preprocess_container__atwork(&$variables) {
	global $base_url;
	$current_path = \Drupal::service('path.current')->getPath();
	// Check if this is a group join page
	if(preg_match("$\/(group)\/[0-9]+\/(join)$", $current_path, $test)){
		if(isset($variables['element']) && $variables['element']['#id'] = "edit-path-wrapper" && $variables['element']['#type'] != 'actions') {
			// This is a input field that the group module is adding. This was the only way i could figure out to get rid of it.
			$variables['children'] = NULL;
			$variables['join_group'] = TRUE;
			$variables['group_link'] = $base_url . substr($current_path , 0,-5);
		}
	}
	if(preg_match("$\/(group)\/[0-9]+\/(leave)$", $current_path, $test)){
		$variables['leave_group'] = TRUE;
		$variables['group_link'] = $base_url . substr($current_path , 0,-6);
	}
}

/**
 * Implements hook_preprocess_HOOK().
 *
 */
function atwork_group_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	if($form_id == "group_content_atwork_groups-group_membership_group-join_form") {
	  $form['actions']['submit']['#submit'][] = 'atwork_group_join_group_submit';
	}
}

/**
 * Implements custom submit handler forgroup join form
 */
function atwork_group_join_group_submit(array $form, FormStateInterface $form_state){
	// Set redirect back to the oiginal group page.
	$route_params = $form_state->getRedirect()->getRouteParameters();
	$form_state->setRedirect('entity.group.canonical', ['group' => $route_params['group']]);
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 * 
 */
function atworknext_theme_suggestions_breadcrumb_alter(array &$suggestions, array $variables) {
	if ($node = \Drupal::routeMatch()->getParameter('node')) {
		$content_type = $node->bundle();
		$suggestions[] = 'breadcrumb__'.$content_type;
	}
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function atworknext_theme_suggestions_container_alter(array &$suggestions, array $variables) {
	$suggestions[] = 'container__' . 'atwork';
}
