idir_ftp_location: ftp.dir.gov.bc.ca
idir_login_name: psa
idir_login_password: Men@W0rk
idir_filename: idir_test.tsv
form_build_id: form-sPQJuPHHfaocSS51-O0gQAPbQex-sxP0Cxl8G7riMiw
form_token: sEyAjZ-8V9H6CqaUmbiRRIGoOInZfH2gEYR8rZr-M4U
form_id: atwork_idir_update_admin_settings_form
op: 'Save configuration'
action: TransactionType
name: Username
pass: None
mail: Email
login: Username
init: Email
user_picture: None
field_user_title: Title
field_user_surname: Surname
field_user_province: Province
field_user_postal_code: PostalCode
field_user_phone: Phone
field_user_organization_code: OrganizationCode
field_user_offic: Office
field_user_given_name: Givenname
field_user_display_name: Displayname
field_user_department: Department
field_user_city: City
field_street: Street
field_company: Company
field_user_guid: GUID
field_blog_bio: None
field_about_me: None
field_job_function_code: HrJobFunctionCode
