idir_ftp_location: ftp.dir.gov.bc.ca
idir_login_name: psa
idir_login_password: Men@W0rk
idir_filename: idir.tsv
form_build_id: form-Ycy_IAtWEP89Dm3bE5ZV5ZGobCojs8E6yNIQLSuSC_0
form_token: oHFuUCIXwA4nhXvY5tfUMsnJLsIIsKeZuNVU1cqcDQE
form_id: atwork_idir_update_admin_settings_form
op: 'Save configuration'
action: TransactionType
name: Username
pass: None
mail: Email
login: Username
init: Email
user_picture: None
field_user_title: Title
field_user_surname: Surname
field_user_province: Province
field_user_postal_code: PostalCode
field_user_phone: Phone
field_user_organization_code: OrganizationCode
field_user_offic: Office
field_user_given_name: Givenname
field_user_display_name: Displayname
field_user_department: Department
field_user_city: City
field_street: Street
field_company: Company
field_user_guid: GUID
