favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://atwork8.local/themes/custom/atworknext/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  atworknext: 8000
breadcrumb_home: 1
button_size: btn-sm
modal_size: ''
modal_enabled: 1
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
table: ''
