palette:
  top: '#10233c'
  bottom: '#10233c'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#cccccc'
  footer: '#10233c'
  button: '#10233c'
  buttonhover: '#016c83'
  titleslogan: '#FFFFFF'
  text: '#333333'
  link: '#406b93'
logo: 'public://color/atwork_barrio-fb802c72/logo.svg'
stylesheets:
  - 'public://color/atwork_barrio-fb802c72/colors.css'
files:
  - 'public://color/atwork_barrio-fb802c72/logo.svg'
  - 'public://color/atwork_barrio-fb802c72/colors.css'
