ignored_config_entities:
  0: siteminder.settings
  2: core.extension
  4: config_ignore.settings
  6: 'welcome.adminsettings '
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
