module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  animated_scroll_to_top: 0
  atwork_article: 0
  atwork_comments: 0
  atwork_extra_fields: 0
  atwork_group: 0
  atwork_h5p: 0
  atwork_idir_update: 0
  atwork_mail_send_update: 0
  atwork_messages: 0
  atwork_poll: 0
  atwork_profiles: 0
  atwork_program_pages: 0
  atwork_tokens: 0
  background_image: 0
  background_image_formatter: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  colorbox: 0
  colorbox_inline: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_entity_updates: 0
  devel_generate: 0
  draggable_dashboard: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  entity: 0
  entity_embed: 0
  entity_reference_revisions: 0
  externalauth: 0
  extra_field: 0
  extrafield_views_integration: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  focal_point: 0
  forward: 0
  gnode: 0
  group: 0
  h5p: 0
  h5peditor: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  inline_form_errors: 0
  insert: 0
  kint: 0
  language: 0
  layout_discovery: 0
  libraries: 0
  like_dislike: 0
  likeit: 0
  link: 0
  linkit: 0
  mailsystem: 0
  matomo: 0
  maxlength: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_export: 0
  menu_item_extras: 0
  menu_link_attributes: 0
  menu_ui: 0
  message: 0
  message_digest: 0
  message_digest_ui: 0
  message_notify: 0
  message_notify_ui: 0
  message_subscribe: 0
  message_subscribe_email: 0
  message_subscribe_ui: 0
  message_ui: 0
  mimemail: 0
  module_filter: 0
  node: 0
  options: 0
  page_cache: 0
  panelizer: 0
  panelizer_quickedit: 0
  panels: 0
  panels_ipe: 0
  paragraphs_type_permissions: 0
  path: 0
  photos: 0
  photos_access: 0
  poll: 0
  postal_code: 0
  queue_ui: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  reroute_email: 0
  responsive_image: 0
  rest: 0
  rules: 0
  scheduler: 0
  search_api: 0
  search_api_sorts: 0
  search_api_stats: 0
  search_api_stats_block: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  simplenews: 0
  simplify_menu: 0
  siteminder: 0
  statistics: 0
  superfish: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  taxonomy_permissions: 0
  telephone: 0
  term_csv_export_import: 0
  tether_stats: 0
  text: 0
  title_field_for_manage_display: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  typed_data: 0
  ultimate_cron: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_wysiwyg: 0
  views_data_export: 0
  views_infinite_scroll: 0
  views_ui: 0
  viewsreference: 0
  webprofiler: 0
  forum: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  bootstrap: 0
  atworknext: 0
  bartik: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
