definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: -70
  node__add_page:
    weight: -50
    menu_name: tools
    parent: ''
    enabled: true
    expanded: false
  filter__tips_all:
    weight: -47
    menu_name: tools
    parent: ''
    expanded: false
    enabled: false
  forum__index:
    weight: -49
    menu_name: tools
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
