toolbar_items:
  - devel.cache_clear
  - devel.container_info.service
  - devel.admin_settings_link
  - devel.field_info_page
  - devel.phpinfo
  - devel.menu_rebuild
  - devel.route_info
  - devel.run_cron
_core:
  default_config_hash: ysHEvvazIuaJ5BdY0dUw2_my_Q5hM8ypdXwFfaIrvMw
