applies_admin_routes: true
include_invalid_paths: false
excluded_paths: ''
replaced_titles: ''
custom_paths: ''
segments_separator: null
include_home_segment: true
home_segment_title: 'Front Page'
home_segment_keep: false
include_title_segment: true
title_segment_as_link: false
title_from_page_when_available: true
language_path_prefix_as_segment: false
use_menu_title_as_fallback: false
use_page_title_as_menu_title_fallback: true
remove_repeated_segments: true
absolute_paths: false
hide_single_home_item: false
term_hierarchy: false
