theme: current
defaults:
  sender: devel_mail_log
  formatter: devel_mail_log
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  message_digest: {  }
  message_notify: {  }
