photos_access_photos: true
photos_additional_sizes: 6
photos_comment: true
photos_cover_imagesize: max_325x325
photos_display_full_imagesize: gallery_image
photos_display_full_viewnum: 8
photos_display_imageorder: created|desc
photos_display_list_imagesize: large
photos_display_page_display: 3
photos_display_page_user: false
photos_display_teaser_display: 3
photos_display_teaser_imagesize: large
photos_display_teaser_user: false
photos_display_teaser_viewnum: 10
photos_display_user: false
photos_display_view_imagesize: gallery_image
photos_display_viewpager: 8
photos_exif: true
photos_exif_cache: false
photos_image_count: true
photos_num: 5
photos_pager_imagesize: medium
photos_path: photos/image_%uid
photos_plupload_status: false
photos_private_file_styles: automatic
photos_rname: false
photos_size:
  thumbnail: Small
  max_650x650: Large
  large: Medium
  gallery_image: 'Gallery Crop'
photos_size_max: ''
photos_upzip: true
photos_user_count_cron: true
photos_pnum_authenticated: 10
photos_pnum_administrator: 10
_core:
  default_config_hash: wn3MckoW6ul8OjY7YTtcEPNpQDGSEyeqd4l9Nj8X_xg
photos_album_column_count: 4
photos_album_display_type: grid
photos_display_colorbox_max_height: 100
photos_display_colorbox_max_width: 100
