user:
  username_mapping: HTTP_SM_USER
  username_mapping_field: name
  id_mapping: HTTP_SMGOV_USERGUID
  guid_mapping: field_user_guid
  username_form: 0
  username_duplicate: 0
  dn_required: 1
  dn_mapping: HTTP_SM_USERDN
  email_required: 1
  usertype_mapping: HTTP_SMGOV_USERTYPE
  mail_mapping: HTTP_SMGOV_USEREMAIL
  sync_everytime: 0
  auth_group: ;
  prefix_strip: false
  domain_strip: false
  role_mapping: ''
  role_evaluate_everytime: false
  new_user_validation: 0
  pending_message: Validating...
  disable_url: 0
  excluded_url: ''
siteminder_cookie: SMSESSION
