active: true
filter:
  mode: include
  rules:
    route:
      - 'quickedit.*'
      - 'history.*'
      - contextual.render
      - entity.node.preview
      - tether_stats.chart.data
    url:
      - poll/%
allow_query_string_elements: false
chart_plugin: tether_stats_google_charts
advanced:
  element_ttl: 432000
  first_activation_time: 1534536887
_core:
  default_config_hash: uqi5IewGqDugxwliOJfgelqPOG3WgSzaEf1mDZpKt60
