cancel_confirm:
  body: ''
  subject: ''
password_reset:
  body: ''
  subject: ''
register_admin_created:
  body: ''
  subject: ''
register_no_approval_required:
  body: ''
  subject: ''
register_pending_approval:
  body: ''
  subject: ''
register_pending_approval_admin:
  body: ''
  subject: ''
status_activated:
  body: "[user:display-name],\r\n\r\nYour account at [site:name] has been activated.\r\n\r\nYou may now log in by clicking this link or copying and pasting it into your browser:\r\n\r\n[user:one-time-login-url]\r\n\r\nThis link can only be used once to log in and will lead you to a page where you can set your password.\r\n\r\nAfter setting your password, you will be able to log in at [site:login-url] in the future using:\r\n\r\nusername: [user:account-name]\r\npassword: Your password\r\n\r\n--  [site:name] team"
  subject: 'Account details for [user:display-name] at [site:name] (approved)'
status_blocked:
  body: "[user:display-name],\r\n\r\nYour account on [site:name] has been blocked.\r\n\r\n--  [site:name] team"
  subject: 'Account details for [user:display-name] at [site:name] (blocked)'
status_canceled:
  body: "[user:display-name],\r\n\r\nYour account on [site:name] has been canceled.\r\n\r\n--  [site:name] team"
  subject: 'Account details for [user:display-name] at [site:name] (canceled)'
langcode: en
_core:
  default_config_hash: m4J3ROov32OEquRYGLbx3SpdDGuqx9l_zJtNvihqdCg
