# @file config/schema/rate.views.schema.yml
#
# Schema for the views plugins.

views.filter.rate_filter:
  type: views_filter
  label: 'Rate'

views.filter_value.rate_filter:
  type: views.filter_value.numeric
  label: 'Rate'