rate.settings:
  type: config_object
  label: 'Rate settings'
  mapping:
    use_ajax:
      type: boolean
      label: 'Use AJAX'
    widget_type:
      type: string
      label: 'Widget type'
    enabled_types_widgets:
      type: sequence
      label: 'Enabled entity types and widgets'
      sequence:
        type: sequence
        label: 'Bundle'
        sequence:
          type: mapping
          label: 'Entity'
          mapping:
            widget_type:
              type: string
              label: 'Widget type'
            entity_type_id:
              type: string
              label: 'Entity Type'
            use_ajax:
              type: boolean
              label: 'Use AJAX'
    bot_minute_threshold:
      type: string
      label: 'Bot minute threshold'
    bot_hour_threshold:
      type: string
      label: 'Bot hour threshold'
    botscout_key:
      type: string
      label: 'BotScout.com API key'
