rate.settings:
  type: config_object
  label: 'Rate settings'
  mapping:
    use_ajax:
      type: boolean
      label: 'Use AJAX'
    widget_type:
      type: string
      label: 'Widget type'
    # @todo Move this to 3rd party settings on the entity itself.
    enabled_types_bundles:
      type: sequence
      label: 'Enabled entity types and bundles'
      sequence:
        type: sequence
        label: 'Entity type'
        sequence:
          type: string
          label: 'Bundle'
