<?php

/**
 * @file
 * views_fs Views module help and theme functions.
 */

// Store views_fs preprocess theme functions in a separate .inc file.
\Drupal::moduleHandler()->loadInclude('views_fs', 'inc', 'views_fs.theme');

/**
 * Implements hook_theme().
 */
function views_fs_theme($existing, $type, $theme, $path) {
  return array(
    'views_fs' => array(
      'file' => 'views_fs.theme.inc',
    ),
  );
}
