# Schema for the configuration files of the photos module.

photos.settings:
  type: config_object
  label: 'Photos settings'
  mapping:
    photos_access_photos:
      type: boolean
      label: 'Enable photos access.'
    photos_additional_sizes:
      type: integer
      label: 'Number of sizes to select from.'
    photos_album_column_count:
      type: integer
      label: 'Number of columns in album grid view.'
    photos_album_display_type:
      type: string
      label: 'Album display type, list or grid.'
    photos_comment:
      type: boolean
      label: 'Enable comment form.'
    photos_cover_imagesize:
      type: string
      label: 'Default cover image size.'
    photos_display_colorbox_max_height:
      type: integer
      label: 'Default max height for colorbox galleries.'
    photos_display_colorbox_max_width:
      type: integer
      label: 'Default max width for colorbox galleries.'
    photos_display_full_imagesize:
      type: string
      label: 'Default full view image size.'
    photos_display_full_viewnum:
      type: integer
      label: 'Default number of thumbnails to display on full node view.'
    photos_display_imageorder:
      type: string
      label: 'Default image order.'
    photos_display_list_imagesize:
      type: string
      label: 'Default image style on album list view.'
    photos_display_page_display:
      type: integer
      label: 'Type of display on node full view.'
    photos_display_page_user:
      type: boolean
      label: 'Allow user to edit node page settings.'
    photos_display_teaser_display:
      type: integer
      label: 'Type of display on node teaser view.'
    photos_display_teaser_imagesize:
      type: string
      label: 'Default image style for node teaser view.'
    photos_display_teaser_user:
      type: boolean
      label: 'Allow user to edit teaser settings.'
    photos_display_teaser_viewnum:
      type: integer
      label: 'Default number of thumbnails to display on teaser node view.'
    photos_display_user:
      type: boolean
      label: 'Allow user to edit individual album settings.'
    photos_display_view_imagesize:
      type: string
      label: 'Default image style for album view.'
    photos_display_viewpager:
      type: integer
      label: 'Number of images to display on album page.'
    photos_exif:
      type: boolean
      label: 'Enable image exif data.'
    photos_exif_cache:
      type: boolean
      label: 'Cache image exif data.'
    photos_image_count:
      type: boolean
      label: 'Enable image count.'
    photos_num:
      type: integer
      label: 'Number of fields on the classic upload form.'
    photos_pager_imagesize:
      type: string
      label: 'Image style for photo information block pager.'
    photos_path:
      type: string
      label: 'Default image upload directory.'
    photos_plupload_status:
      type: boolean
      label: 'Enable plupload module integration.'
    photos_private_file_styles:
      type: string
      label: 'Private image style setting.'
    photos_rname:
      type: boolean
      label: 'Enable image file renaming feature.'
    photos_size:
      type: sequence
      label: 'Image style options available in album node settings.'
      sequence:
        type: string
        label: 'Image style.'
    photos_size_max:
      type: string
      label: 'Maximum image dimensions.'
    photos_upzip:
      type: boolean
      label: 'Enable zip file upload.'
    photos_user_count_cron:
      type: boolean
      label: 'Enable image count during cron.'
    photos_pnum_authenticated:
      type: integer
      label: 'Default number of albums allowed for authenticated users.'
    photos_pnum_administrator:
      type: integer
      label: 'Default number of albums allowed for administrator users.'
