<?php

/**
 * @file
 * Functions to support theming in Seeds Root theme.
 */
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 */
function root_preprocess_html(&$variables) {
  $variables['attributes']['class'][] = 'seeds-root';
  // Load rtl style.
  if ($variables['html_attributes']['dir'] == 'rtl') {
    $variables['page']['#attached']['library'][] = 'root/rtl';
  }
}
