synonyms.synonym.*:
  type: config_entity
  label: 'Synonym configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    provider_plugin:
      type: string
      label: 'Controlled provider plugin'
    base_provider_plugin:
      type: string
      label: 'Base ID of the controlled provider plugin'
    provider_configuration:
      type: synonyms.provider.[%parent.base_provider_plugin]
      label: 'Configuration of provider plugin'
    behavior:
      type: string
      label: 'Controlled behavior service'
    behavior_configuration:
      type: synonyms.[%parent.behavior]
      label: 'Configuration of behavior service'
