<?php

/**
 * @file
 * Primary module hooks for atwork_article module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function atwork_article_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	
		if($form["#form_id"] == $form_id) {
			
			// Add instructions to Article Title field
			$form['title']['widget'][0]['value']['#description'] = 'Enter the title for the article. This will 
				appear at the top of the article and on the home page. 
				Note, the maximum character length, including spaces, is <strong>60</strong>. ';
		
		}
		
		
	//if (isset($form['type']) && $form['type']['#value'] . '_node_settings' == $form_id) {
	//	$upload_enabled_types = \Drupal::config('mymodule.settings')
	//	->get('upload_enabled_types');
	//	$form['workflow']['upload_' . $form['type']['#value']] = array(
	//			'#type' => 'radios',
	//			'#title' => t('Attachments'),
	//			'#default_value' => in_array($form['type']['#value'], $upload_enabled_types) ? 1 : 0,
	//			'#options' => array(
	//					t('Disabled'),
	//					t('Enabled'),
	//			),
	//	);
	//	
	//	// Add a custom submit handler to save the array of types back to the config file.
	//	$form['actions']['submit']['#submit'][] = 'mymodule_upload_enabled_types_submit';
	//}
}