<?php

/**
 * @file
 * Primary module hooks for atwork_article module.
 * 
 */
function atwork_article_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	if(($form["#form_id"] == $form_id) && (in_array($form["#form_id"], array('node_article_form','node_article_edit_form')))) {
		// Attach custom module javascript library
    $form['#attached']['library'][] = 'atwork_article/atwork_article';
  
	  // Add instructions to Article Title field
	  $form['title']['widget'][0]['value']['#description'] = t('Enter the title for the article. This will 
	  	appear at the top of the article and on the home page. 
	  	Note, the maximum character length, including spaces, is <strong>60</strong>. ');
	  
	  // Modify title and instructions for article teaser.
	  $form['body']['widget'][0]['summary']['#title'] = t('Teaser');
	  $form['body']['widget'][0]['summary']['#description'] = t('Enter the teaser for the article. Note, 
	  	the maximum character length, including spaces, is 300. The teaser will be posted to the home 
	  	page along with the image and title of the article to encourage employees to read the full 
	  	article. There will be a link to the full article available on the home page. ');
	}
}


/**
 * Implements hook_theme_registry_alter().
 */
function atwork_article_theme_registry_alter(&$theme_registry) {
	// Load custom file-upload-help twig template with custom instructions
  $theme_registry['file_upload_help']['path'] = 'themes/custom/atworknext/templates';
}


/**
 * Implements hook_preprocess_HOOK().
 */
function atworknext_preprocess_node__article(&$variables) {
	if($variables['elements']['field_author_information'][0]['#title'] == 'Employee News') {
		$variables['isEmployeeNews'] = True;
	}
}