text:
  -
    value: "<p>Hi @user_name,</p>\r\n\r\n<p>Here are the latest results from your @Work subscriptions:</p>\r\n\r\n<p><a href=\"javascript:void(0);\" title=\"Insert this token into your form\">[view:title]</a></p>\r\n"
    format: comment_editor
