<<<<<<< HEAD:config/sync/block.block.programareamenu.yml
uuid: e7e09875-a4e7-4684-a22d-43b8f8a743e2
=======
uuid: 606826ad-9b31-4727-bd35-920d6f25f6b2
>>>>>>> work_next/kanopi_merge_branch:config/block.block.program_area_sidebar_menu.yml
langcode: en
status: true
dependencies:
  module:
    - ctools
  theme:
<<<<<<< HEAD:config/sync/block.block.programareamenu.yml
    - atwork_barrio
id: programareamenu
theme: atwork_barrio
region: sidebar_first
weight: 0
=======
    - atworknext
id: program_area_sidebar_menu
theme: atworknext
region: sidebar_nav
weight: -11
>>>>>>> work_next/kanopi_merge_branch:config/block.block.program_area_sidebar_menu.yml
provider: null
plugin: 'block_content:6f0fae91-2b6f-4afb-bce4-7ba1479ba701'
settings:
  id: 'block_content:6f0fae91-2b6f-4afb-bce4-7ba1479ba701'
  label: 'Program Area Sidebar Menu'
  provider: core
  label_display: '0'
  status: true
  info: ''
  view_mode: full
visibility:
  'entity_bundle:node':
    id: 'entity_bundle:node'
    bundles:
      program_area_content: program_area_content
    negate: false
    context_mapping:
      node: '@node.node_route_context:node'
