<?php

use Drupal\Core\Url;
use Drupal\user_alert\Entity\UserAlert;

/**
 * Implements hook_theme().
 */
function user_alert_theme() {
  return array(
    'user_alert_add_list' => array(
      'variables' => array(
        'content' => NULL
      ),
		),
		'user_alert_message' => array(
      'variables' => array(
        'alert' => NULL,
        'id' => NULL,
        'is_closeable' => FALSE,
      ),
    ),
  );
}

/**
 * Prepares variables for list of available node type templates.
 *
 * Default template: node-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of content types.
 *
 * @see node_add_page()
 */
function template_preprocess_user_alert_add_list(&$variables) {
  $variables['types'] = array();
  if (!empty($variables['content'])) {
		foreach ($variables['content'] as $type) {
			$variables['types'][$type->id()] = array(
				'type' => $type->id(),
				'add_link' => \Drupal::l($type->label(), new Url('entity.user_alert.add', array('user_alert_type' => $type->id()))),
				'description' => array(
					'#markup' => $type->getDescription(),
				),
			);
		}
  }
}

