<?php
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */
function atworknext_preprocess_links(&$variables){
  $variables['links_new'] = $variables['links'];
}

/**
 * Implements hook_preprocess_html().
 */
function atworknext_preprocess_html(&$variables) {

  if ($node = \Drupal::routeMatch()->getParameter('node_preview')) {
    $variables['attributes']['class'][] = 'atwork-node-preview';
  }
}
