<?php

/**
 * @file
 * Contains content_segmentation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function content_segmentation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_segmentation module.
    case 'help.page.content_segmentation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('BC Content Segmentation - EMPC') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function content_segmentation_preprocess_views_view(&$variables) {
  // add form before the view,
  // this is a alternative to print the form in DefaultController, keep only one variant
  if ($variables['id'] == 'content_emp' && $variables['display_id'] == 'page_1' ) {
  	$form = \Drupal::formBuilder()->getForm('\Drupal\content_segmentation\Form\CorporateNewsEmp');
  	$variables['attachment_after'][] = $form;
  }
  if ($variables['id'] == 'content_emp' && $variables['display_id'] == 'page_2' ) {
    $form = \Drupal::formBuilder()->getForm('\Drupal\content_segmentation\Form\MessagesEmp');
    $variables['attachment_after'][] = $form;
  }
}

/**
 * @file
 * Contains draggableviews.module.
 */

//use Drupal\draggableviews\DraggableViews;
//use Drupal\Core\Form\FormStateInterface;
//use Drupal\Core\Database\Database;
//use Drupal\Core\Cache\Cache;

/**
 * Implements hook_views_data_alter().
 */
//function content_segmentation_views_data_alter(&$data) {
//  $data['draggableviews_structure']['weight']['sort'] = [
//  	  'field' => 'field_current_user_segmentation', 
//      'id' => 'segmentation',
//    ];
//}
/**
 * Implements hook_views_data_alter().
 */
function content_segmentation_views_data_alter(array &$data) {
  $data['draggableviews_structure']['content_segmentation_user'] = [
    'title' => t('Content Segmentation User'),
    'group' => t('Draggableviews'),
    'field' => [
      'title' => t('Content Segmentation User'),
      'help' => t('Content Segmentation User'),
      'id' => 'content_segmentation_user',
    ],
    'sort' => [
      'id' => 'standard',
    ],
  ];
}

